# Generated by Django 6.0.7 on 2026-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_background', 'Hero background'), ('hero_feature', 'Hero featured image'), ('about_story', 'About section image'), ('showcase', 'Showcase image'), ('gallery', 'Gallery image')], max_length=32)),
                ('image', models.ImageField(upload_to='section_images/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Section image',
                'verbose_name_plural': 'Section images',
                'ordering': ['section', 'sort_order'],
            },
        ),
    ]
