# Generated by Django 6.0.7 on 2026-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pagesectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesectionimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption or alt text for the image.', max_length=128),
        ),
        migrations.AlterField(
            model_name='pagesectionimage',
            name='image',
            field=models.ImageField(help_text='Upload the image for this page section.', upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='pagesectionimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower values appear before higher values when multiple items are allowed.'),
        ),
        migrations.AddConstraint(
            model_name='pagesectionimage',
            constraint=models.UniqueConstraint(condition=models.Q(('section__in', ['hero_background', 'hero_feature', 'about_story', 'showcase'])), fields=('section',), name='unique_single_image_section'),
        ),
    ]
